esphome:
  name: marstek-jupiter-e
  friendly_name: Marstek Jupiter E

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable OTA Update
ota:
  - platform: esphome
    password: !secret wifi_password

# Enable Web-Server
web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Marstek-Jupiter-E"
    password: !secret wifi_password

captive_portal:

# UART Definition
uart:
  id: mod_bus
  tx_pin: GPIO22
  rx_pin: GPIO21
  baud_rate: 115200
  stop_bits: 1

# Modbus Definition
modbus:
  id: modbus1
  uart_id: mod_bus

modbus_controller:
# Update Interval 5 Sec
- id: modbus_device
  address: 0x1
  modbus_id: modbus1
  setup_priority: -10
  update_interval: 5s

# Update Interval 1 Min
- id: modbus_device_slow
  address: 0x1
  modbus_id: modbus1
  setup_priority: -10
  update_interval: 60s

# Update Interval 5 Min
- id: modbus_device_very_slow
  address: 0x1
  modbus_id: modbus1
  setup_priority: -10
  update_interval: 300s

sensor:
# PV 1
- platform: modbus_controller
  modbus_controller_id: modbus_device_slow
  name: "pv 1 voltage"
  register_type: holding
  address: 0x0001
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device_slow
  name: "pv 1 current"
  register_type: holding
  address: 0x0002
  unit_of_measurement: "A"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "pv 1 power"
  register_type: holding
  address: 0x0003
  unit_of_measurement: "W"
  value_type: U_WORD

# PV 2
- platform: modbus_controller
  modbus_controller_id: modbus_device_slow
  name: "pv 2 voltage"
  register_type: holding
  address: 0x0004
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device_slow
  name: "pv 2 current"
  register_type: holding
  address: 0x0005
  unit_of_measurement: "A"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "pv 2 power"
  register_type: holding
  address: 0x0006
  unit_of_measurement: "W"
  value_type: U_WORD

# PV 3
- platform: modbus_controller
  modbus_controller_id: modbus_device_slow
  name: "pv 3 voltage"
  register_type: holding
  address: 0x0007
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device_slow
  name: "pv 3 current"
  register_type: holding
  address: 0x0008
  unit_of_measurement: "A"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "pv 3 power"
  register_type: holding
  address: 0x0009
  unit_of_measurement: "W"
  value_type: U_WORD

# PV 4
- platform: modbus_controller
  modbus_controller_id: modbus_device_slow
  name: "pv 4 voltage"
  register_type: holding
  address: 0x000A
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device_slow
  name: "pv 4 current"
  register_type: holding
  address: 0x000B
  unit_of_measurement: "A"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "pv 4 power"
  register_type: holding
  address: 0x000C
  unit_of_measurement: "W"
  value_type: U_WORD

# Grid Power
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "grid power"
  register_type: holding
  address: 0x0000D
  unit_of_measurement: "W"
  value_type: U_WORD

# Battery Voltage
- platform: modbus_controller
  modbus_controller_id: modbus_device_very_slow
  name: "battery voltage"
  register_type: holding
  address: 0x000F
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.1

# Battery SOC
- platform: modbus_controller
  modbus_controller_id: modbus_device_very_slow
  name: "battery soc"
  register_type: holding
  address: 0x0010
  unit_of_measurement: "%"
  value_type: U_WORD

# Daily Power Generation
- platform: modbus_controller
  modbus_controller_id: modbus_device_very_slow
  name: "daily power generation"
  register_type: holding
  address: 0x0013
  unit_of_measurement: "kWh"
  value_type: U_DWORD
  accuracy_decimals: 2
  filters:
  - multiply: 0.01

# Monthly Power Generation
- platform: modbus_controller
  modbus_controller_id: modbus_device_very_slow
  name: "monthly power generation"
  register_type: holding
  address: 0x0015
  unit_of_measurement: "kWh"
  value_type: U_DWORD
  accuracy_decimals: 2
  filters:
  - multiply: 0.01

# Daily Grid Connected Electricity
- platform: modbus_controller
  modbus_controller_id: modbus_device_slow
  name: "daily grid connected electricity"
  register_type: holding
  address: 0x0017
  unit_of_measurement: "kWh"
  value_type: U_DWORD
  accuracy_decimals: 2
  filters:
  - multiply: 0.01

# Monthly Grid Connected Electricity
- platform: modbus_controller
  modbus_controller_id: modbus_device_slow
  name: "monthly grid connected electricity"
  register_type: holding
  address: 0x0019
  unit_of_measurement: "kWh"
  value_type: U_DWORD
  accuracy_decimals: 2
  filters:
  - multiply: 0.01
